# Generated by Django 3.2.10 on 2022-05-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_schoolclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Schools',
        ),
    ]
