# Generated by Django 3.2.10 on 2022-05-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20220528_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
