# Generated by Django 3.2.10 on 2022-05-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20220528_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
