# Generated by Django 3.2.10 on 2022-05-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20220528_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='School',
        ),
    ]
