# Generated by Django 3.2.10 on 2022-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_rename_schools_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('number_phone', models.CharField(max_length=255)),
                ('name_parrent1', models.CharField(max_length=255)),
                ('name_parrent2', models.CharField(max_length=255)),
                ('number_phone_parrent1', models.CharField(max_length=255)),
                ('number_phone_parrent2', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('marks', models.JSONField()),
                ('work_parrent1', models.CharField(max_length=255)),
                ('work_parrent2', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
