# Generated by Django 3.2.10 on 2022-06-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='School1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('town', models.CharField(max_length=255)),
                ('clases', models.JSONField()),
                ('lessons', models.JSONField()),
                ('teachers', models.JSONField()),
                ('class_form', models.JSONField()),
                ('lesson_form', models.JSONField()),
                ('password', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
