# Generated by Django 3.2.10 on 2022-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_alter_school_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='teachers',
            field=models.JSONField(default={'teachers': []}),
        ),
    ]
