# Generated by Django 3.2.10 on 2022-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_alter_school_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(default='На цьому місці може бути ваша реклама', max_length=255)),
                ('text2', models.CharField(default='На цьому також', max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='news_text1',
            field=models.CharField(default='На цьому місці ви можете дізнатися останні новини вашої школи', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='news_text2',
            field=models.CharField(default='А це на випадок якщо новин занадто багато', max_length=255),
        ),
    ]
