# Generated by Django 3.2.10 on 2022-06-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_auto_20220621_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text1',
            field=models.CharField(default='На цьому місці може бути ваша реклама', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='text2',
            field=models.CharField(default='На цьому також', max_length=1000),
        ),
        migrations.AlterField(
            model_name='school',
            name='news_text1',
            field=models.CharField(default='На цьому місці ви можете дізнатися останні новини вашої школи', max_length=1000),
        ),
        migrations.AlterField(
            model_name='school',
            name='news_text2',
            field=models.CharField(default='А це на випадок якщо новин занадто багато', max_length=1000),
        ),
    ]
