# Generated by Django 3.2.10 on 2022-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_auto_20220621_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='login',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
