# Generated by Django 3.2.10 on 2022-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_auto_20220630_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='login',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
