# Generated by Django 3.2.10 on 2022-07-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_auto_20220630_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='adress',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='facebook',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='instagram',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='school_director',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='school_phone',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='school_profil',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='school_site',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
