# Generated by Django 4.0.6 on 2022-07-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book_model',
        ),
    ]
